"""
Django settings for backend_ai project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "XXXXXX")
PUBLIC_KEY = os.getenv("public_key")
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "XXXXXX")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "XXXXXX")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

# Django Environment
DJANGO_ENV = os.getenv("DJANGO_ENV")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")

NEXT_API_SECRET_KEY = os.getenv("NEXT_API_SECRET_KEY")

HTTPS = os.getenv("HTTPS") == "True"
if HTTPS or DJANGO_ENV == "production":
    BACKEND_URL = os.getenv("HTTPS_BACKEND_URL")
    FRONTEND_URL = os.getenv("HTTPS_FRONTEND_URL")
else:
    BACKEND_URL = os.getenv("HTTP_BACKEND_URL")
    FRONTEND_URL = os.getenv("HTTP_FRONTEND_URL")

# Application definition

APP_NAME = os.getenv("APP_NAME")

INSTALLED_APPS = [
    "core_db_ai",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "backend_ai.middlewares.RestrictDirectApiMiddleware",
]

ROOT_URLCONF = "backend_ai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
            ],
        },
    },
]

WSGI_APPLICATION = "backend_ai.wsgi.application"

PYTHONUNBUFFERED = 1


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE"),
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static_ai/"
STATIC_ROOT = "/app/static_ai"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": ("drf_spectacular.openapi.AutoSchema"),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

# Simple JWT Settings

REST_USE_JWT = True

SIMPLE_JWT = {
    "ALGORITHM": "RS256",
    "VERIFYING_KEY": PUBLIC_KEY,
    "USER_ID_CLAIM": "user_id",
    "AUTH_HEADER_TYPES": ("Bearer",),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Real Estate AI API",
    "DESCRIPTION": "API for Real Estate AI",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [
        {
            "NEXT_API_SECRET_KEY": [],  # Custom API Key
        }
    ],
    # Define the security schemes
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "NEXT_API_SECRET_KEY": {
                "type": "apiKey",
                "in": "header",
                "name": "NEXT-X-API-KEY",
                "description": "NEXT JS Frontend API Key (required alongside JWT)",
            },
        }
    },
}

# CORS Settings

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(
    ","
)

CORS_ALLOW_CREDENTIALS = True

# CSRF Settings

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000").split(
    ","
)

CSRF_COOKIE_SECURE = True  # Ensures the CSRF cookie is sent only over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Must be False since JavaScript needs to read the token
CSRF_COOKIE_SAMESITE = "Lax"  # Prevent cross-origin requests
CSRF_COOKIE_AGE = 60 * 60 * 24  # 1 day

# Database Routing
DATABASE_ROUTERS = ["backend_ai.router.SharedDatabaseRouter"]

# Session Settings
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = True  # Secure session cookies

AUTH_USER_MODEL = "core_db_ai.User"

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)  # Only if Nginx is reverse proxied

# Celery Configuration
CELERY_REDIS_HOST = os.getenv("REDIS_HOST", "redis")
CELERY_REDIS_PORT = os.getenv("REDIS_PORT", "6379")
CELERY_BROKER_URL = f"redis://{CELERY_REDIS_HOST}:{CELERY_REDIS_PORT}/2"
CELERY_RESULT_BACKEND = f"redis://{CELERY_REDIS_HOST}:{CELERY_REDIS_PORT}/2"
CELERY_RESULT_EXPIRES = 3600

CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "4"))
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Monitoring

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "console": {
#             "level": "INFO",
#             "class": "logging.StreamHandler",
#             "formatter": "simple",
#         },
#     },
#     "loggers": {
#         "": {  # Root logger
#             "level": "INFO",
#             "handlers": ["console"],
#         },
#         "django": {  # Django-specific logger
#             "level": "INFO",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#         "botocore": {  # botocore logger (for S3/AWS interactions)
#             "level": "WARNING",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#         "boto3": {  # boto3 logger
#             "level": "WARNING",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#         "s3transfer": {  # s3transfer logger (used by boto3 for file transfers)
#             "level": "WARNING",
#             "handlers": ["console"],
#             "propagate": False,
#         },
#     },
# }
