import {
  kohSantepheap,
  quando,
  oldStandardTT,
  merriweather,
} from "@/styles/fonts";
import "@/styles/globals.css";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`
      ${kohSantepheap.variable} 
      ${quando.variable} 
      ${oldStandardTT.variable} 
      ${merriweather.variable}
    `}
    >
      <body>
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
