# Generated by Django 5.2.6 on 2025-09-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
