# Generated by Django 5.2.6 on 2025-10-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0002_property_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
    ]
