# Generated by Django 5.2.6 on 2025-10-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0003_remove_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
