# Generated by Django 5.2.6 on 2025-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0004_alter_property_slug_alter_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
