# Generated by Django 6.0.1 on 2026-02-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0005_alter_property_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"ordering": ["user__email"]},
        ),
    ]
