# Generated by Django 6.0.1 on 2026-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0006_alter_agent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
