# Generated by Django 6.0.1 on 2026-03-09 17:33

import sys
from django.conf import settings
from django.db import migrations, models

# Determine if we are running tests
IS_TESTING = "test" in sys.argv


class Migration(migrations.Migration):

    dependencies = [
        ("core_db", "0007_alter_property_address_alter_property_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="ai_reports",
                        to=settings.AUTH_USER_MODEL,
                        db_column="user_id",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="ai_reports",
                        to="core_db.property",
                        db_column="property_id",
                    ),
                ),
            ],
            options={
                "db_table": "core_db_ai_aireport",
                "managed": IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        db_column="user_id",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="chat_sessions",
                        to="core_db.aireport",
                        db_column="report_id",
                    ),
                ),
            ],
            options={
                "db_table": "core_db_ai_chatsession",
                "managed": IS_TESTING,
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="messages",
                        to="core_db.chatsession",
                        db_column="session_id",
                    ),
                ),
            ],
            options={
                "db_table": "core_db_ai_chatmessage",
                "managed": IS_TESTING,
            },
        ),
    ]
