# Generated by Django 6.0 on 2025-12-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_agent", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "core_db_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("bio", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "core_db_agent",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("beds", models.IntegerField()),
                ("baths", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("area_sqft", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "core_db_property",
                "managed": False,
            },
        ),
    ]
