# Generated by Django 6.0 on 2025-12-29 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("extracted_area", models.CharField(blank=True, max_length=100)),
                ("extracted_city", models.CharField(blank=True, max_length=100)),
                ("comparable_data", models.JSONField(blank=True, null=True)),
                (
                    "avg_market_price",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "avg_price_per_sqft",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "investment_rating",
                    models.IntegerField(
                        help_text="Rating from 0 to 4 based on price regression",
                        null=True,
                    ),
                ),
                ("ai_insight_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_report",
                        to="core_db_ai.property",
                    ),
                ),
            ],
        ),
    ]
