# Generated by Django 6.0 on 2025-12-30 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0002_aireport"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aireport",
            name="investment_rating",
            field=models.IntegerField(
                help_text="Rating from 0 to 5 based on price regression", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to="core_db_ai.property",
            ),
        ),
    ]
