# Generated by Django 6.0 on 2025-12-30 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0003_aireport_user_alter_aireport_investment_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aireport",
            name="investment_rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Rating from 0.0 to 5.0 based on analysis",
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
