# Generated by Django 6.0 on 2025-12-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0004_alter_aireport_investment_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireport",
            name="avg_baths",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="aireport",
            name="avg_beds",
            field=models.IntegerField(null=True),
        ),
    ]
