# Generated by Django 6.0 on 2026-02-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0006_chatsession_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
