# Generated by Django 6.0 on 2026-02-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_db_ai", "0007_chatmessage_status_alter_chatmessage_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aireport",
            name="ai_insight_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="avg_baths",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="avg_beds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="avg_market_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="avg_price_per_sqft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="extracted_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="extracted_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to="core_db_ai.aireport",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
